### ISSUE TITLE
[question] Best Practices?

### ISSUE THREAD

**Issue by mikegee** [mrThe/to_nil#5]
I installed this gem and started casting objects to nil, but I haven't recouped my initial investment yet. I'm concerned about using the gem improperly. Could you share some pointers, pro tips, and/or life hacks to improve my to_nil usage?

**Comment by carlosbaraza** [comment]
The possibilities are endless. Any usage of this gem is a ruby master best practice. Just as an usage example:

``` ruby
begin
  raise StandardError.to_nil
rescue Exception => e
  puts 'owned'
end
```

**Comment by jomo** [comment]
You can also use this in rails applications, for example:

``` ruby
# Register nil Mime Type
Mime::Type.register "nil/nil", :nil
```

``` ruby
respond_to do |format|
  format.xml { render xml: @person.to_xml }
  format.nil { render text: @person.to_nil }
end
```

**Comment by mikegee** [comment]
Given [The Billion Dollar Mistake](http://en.wikipedia.org/wiki/Tony_Hoare#Apologies_and_retractions), this gem is probably worth about tree fiddy.  I ported my apps to Haskell and deleted Ruby.  Thanks anyway.

**Comment by carlosbaraza** [comment]
Hahaha you guys made my day.
